# Generated by Django 2.0.dev20170323172204 on 2017-03-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170325_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='events',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
